// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Zty9o1jg33xOH6Y1itLaUYGIKMDkyQE',
    appId: '1:576921542305:android:66ca988d264b2003f99ae0',
    messagingSenderId: '576921542305',
    projectId: 'taxibooking-ffe59',
    databaseURL: 'https://taxibooking-ffe59-default-rtdb.firebaseio.com',
    storageBucket: 'taxibooking-ffe59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs60ID12RbG345vVUqAquurZqWqP31RMk',
    appId: '1:576921542305:ios:aa50fb472d86462df99ae0',
    messagingSenderId: '576921542305',
    projectId: 'taxibooking-ffe59',
    databaseURL: 'https://taxibooking-ffe59-default-rtdb.firebaseio.com',
    storageBucket: 'taxibooking-ffe59.appspot.com',
    iosBundleId: 'com.example.driverTaxiBookingApp',
  );
}
